{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 94,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "#for translating webpage\n",
    "from textblob import TextBlob\n",
    "#for scraping the web\n",
    "from bs4 import BeautifulSoup\n",
    "import requests\n",
    "#for ssl certificate error\n",
    "import certifi"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 62,
   "metadata": {},
   "outputs": [],
   "source": [
    "dataset = pd.read_excel('SampleData.xlsx')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 63,
   "metadata": {},
   "outputs": [],
   "source": [
    "dataset = dataset[['id','homepage']]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 72,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id</th>\n",
       "      <th>homepage</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>50390</td>\n",
       "      <td>http://www.oettinger-sportwagen.de/</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2954</td>\n",
       "      <td>http://www.audi-zentrum-dresden.de/</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>5277</td>\n",
       "      <td>http://www.auto-trentzsch.de/</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>6910</td>\n",
       "      <td>http://www.opel-dresden-bremer.de/</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>9476</td>\n",
       "      <td>http://www.opelhaendler.de/autohaus-dresden_dr...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>10929</td>\n",
       "      <td>http://www.hanisch.hyundai.de/</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>330735</td>\n",
       "      <td>http://bmw-partner.bmw.de/autohaus-melkus-dres...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>21155</td>\n",
       "      <td>http://www.ruediger-dresden.skoda-auto.de/</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>517707</td>\n",
       "      <td>http://www.junited-autoglas.de/</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>518826</td>\n",
       "      <td>http://ksautoglas.de/index.php?s=ueber-ks-auto...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       id                                           homepage\n",
       "0   50390                http://www.oettinger-sportwagen.de/\n",
       "1    2954                http://www.audi-zentrum-dresden.de/\n",
       "2    5277                      http://www.auto-trentzsch.de/\n",
       "3    6910                 http://www.opel-dresden-bremer.de/\n",
       "4    9476  http://www.opelhaendler.de/autohaus-dresden_dr...\n",
       "5   10929                     http://www.hanisch.hyundai.de/\n",
       "6  330735  http://bmw-partner.bmw.de/autohaus-melkus-dres...\n",
       "7   21155         http://www.ruediger-dresden.skoda-auto.de/\n",
       "8  517707                    http://www.junited-autoglas.de/\n",
       "9  518826  http://ksautoglas.de/index.php?s=ueber-ks-auto..."
      ]
     },
     "execution_count": 72,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "dataset.head(10)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "200"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "webData = requests.get(dataset.homepage[0])\n",
    "webData.status_code"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "soup = BeautifulSoup(webData.content,'html.parser')\n",
    "soupText = soup.prettify()\n",
    "print(len(soupText))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "deText = soup.find('p')\n",
    "print(deText)\n",
    "deTextBlob = TextBlob(deText.text)\n",
    "deTextBlob.detect_language()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "blob = TextBlob(soupText)\n",
    "blob.\n",
    "Englishstr = blob.translate(from_lang='de',to='en')\n",
    "print('------------------------------------------------')\n",
    "print(Englishstr)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 98,
   "metadata": {},
   "outputs": [],
   "source": [
    "%run ScrapeHeroScraping.ipynb\n",
    "import os\n",
    "notScraped = {}\n",
    "def startScraping(homepages, baseIndex = 0):\n",
    "    for index in range(baseIndex,len(homepages)):\n",
    "        print(index)\n",
    "        try:\n",
    "            response = requests.get(homepages[index], verify = certifi.where())\n",
    "            print('Request Success')\n",
    "            if(response.status_code == 200):\n",
    "                soup = BeautifulSoup(response.content,'html.parser')\n",
    "                print('gathered Soup')\n",
    "                soupText = soup.prettify()\n",
    "                deText = soup.find('p')\n",
    "                print('found deText')\n",
    "                deTextBlob = TextBlob(deText.text)\n",
    "                textLang = deTextBlob.detect_language()\n",
    "                print('Language Detected',textLang)\n",
    "                blob = TextBlob(soupText)\n",
    "                print('created Text Blob')\n",
    "                Englishstr = blob.translate(from_lang=textLang,to='en')\n",
    "                if not os.path.exists('raw_data/%s'%homepages[index][7:]):\n",
    "                    os.makedirs('raw_data/%s'%homepages[index][7:])\n",
    "                file1 = open('raw_data/%s/allSeprateFile.txt'%homepages[index][7:],'w')\n",
    "                file1.writelines(Englishstr)\n",
    "                file1.close()\n",
    "                print('file Written')\n",
    "                response.close()\n",
    "            elif(response.status_code != 200):\n",
    "                notScraped[homepages[index]]=response.status_code\n",
    "                response.close()\n",
    "        except Exception as e:\n",
    "            print('reached exception')\n",
    "            notScraped[homepages[index]]=e\n",
    "            print(e)\n",
    "            response.close()\n",
    "#             continue\n",
    "            \n",
    "#             startScraping(homepages[index+2:len(homepages)])\n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 99,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "4\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "'NoneType' object has no attribute 'text'\n",
      "5\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "'NoneType' object has no attribute 'text'\n",
      "6\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "7\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "8\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "9\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "10\n",
      "reached exception\n",
      "HTTPSConnectionPool(host='www.dresdner-reifen-zentrale.de', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1108)')))\n",
      "11\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected en\n",
      "created Text Blob\n",
      "reached exception\n",
      "Translation API returned the input string unchanged.\n",
      "12\n",
      "reached exception\n",
      "('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n",
      "13\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "14\n",
      "Request Success\n",
      "15\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "Must provide a string with at least 3 characters.\n",
      "16\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "Must provide a string with at least 3 characters.\n",
      "17\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected tr\n",
      "created Text Blob\n",
      "file Written\n",
      "18\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "19\n",
      "Request Success\n",
      "20\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "'NoneType' object has no attribute 'text'\n",
      "21\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "22\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "23\n",
      "reached exception\n",
      "HTTPConnectionPool(host='www.karosserie-zdzieblik-dresden.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f40134a1d00>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "24\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "Must provide a string with at least 3 characters.\n",
      "25\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "26\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "Must provide a string with at least 3 characters.\n",
      "27\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "28\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "'NoneType' object has no attribute 'text'\n",
      "29\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "Must provide a string with at least 3 characters.\n",
      "30\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "'NoneType' object has no attribute 'text'\n",
      "31\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected en\n",
      "created Text Blob\n",
      "reached exception\n",
      "Translation API returned the input string unchanged.\n",
      "32\n",
      "Request Success\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "33\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "'NoneType' object has no attribute 'text'\n",
      "34\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "35\n",
      "reached exception\n",
      "HTTPConnectionPool(host='www.partner.volvocars.de', port=80): Max retries exceeded with url: /sachsengarage/dresdner-heide/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4012e00940>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
      "36\n",
      "reached exception\n",
      "HTTPConnectionPool(host='www.schiemann.hyundai.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4012e091f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "37\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "Must provide a string with at least 3 characters.\n",
      "38\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected en\n",
      "created Text Blob\n",
      "reached exception\n",
      "Translation API returned the input string unchanged.\n",
      "39\n",
      "reached exception\n",
      "HTTPConnectionPool(host='www.gloeckner.chrysler.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f40137aa730>: Failed to establish a new connection: [Errno 113] No route to host'))\n",
      "40\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "'NoneType' object has no attribute 'text'\n",
      "41\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "'NoneType' object has no attribute 'text'\n",
      "42\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "43\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "'NoneType' object has no attribute 'text'\n",
      "44\n",
      "Request Success\n",
      "45\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "46\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "'NoneType' object has no attribute 'text'\n",
      "47\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "48\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "49\n",
      "Request Success\n",
      "50\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "51\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected en\n",
      "created Text Blob\n",
      "reached exception\n",
      "Translation API returned the input string unchanged.\n",
      "52\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "53\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "Must provide a string with at least 3 characters.\n",
      "54\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "Must provide a string with at least 3 characters.\n",
      "55\n",
      "reached exception\n",
      "HTTPConnectionPool(host='www.ams-hannss.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f40144d6340>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "56\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "57\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected fr\n",
      "created Text Blob\n",
      "file Written\n",
      "58\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected en\n",
      "created Text Blob\n",
      "reached exception\n",
      "Translation API returned the input string unchanged.\n",
      "59\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "60\n",
      "Request Success\n",
      "61\n",
      "Request Success\n",
      "62\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected en\n",
      "created Text Blob\n",
      "reached exception\n",
      "Translation API returned the input string unchanged.\n",
      "63\n",
      "reached exception\n",
      "HTTPSConnectionPool(host='strehle.kiapartner.de', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(\"hostname 'strehle.kiapartner.de' doesn't match either of 'mk.kia-dws.de', 'www.mk.kia-dws.de'\")))\n",
      "64\n",
      "reached exception\n",
      "HTTPConnectionPool(host='www.citroen-haendler.de', port=80): Max retries exceeded with url: /heider-dresden/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4012f8d0a0>: Failed to establish a new connection: [Errno 110] Connection timed out'))\n",
      "65\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "'NoneType' object has no attribute 'text'\n",
      "66\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "67\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "68\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "69\n",
      "reached exception\n",
      "('Connection aborted.', OSError(0, 'Error'))\n",
      "70\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "71\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "72\n",
      "reached exception\n",
      "HTTPConnectionPool(host='www.saab-erleben.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4013fab1f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "73\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "74\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "75\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "'NoneType' object has no attribute 'text'\n",
      "76\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "77\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "78\n",
      "reached exception\n",
      "HTTPConnectionPool(host='www.citroen-haendler.de', port=80): Max retries exceeded with url: /bernhardt-dresden/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4013ef63a0>: Failed to establish a new connection: [Errno 110] Connection timed out'))\n",
      "79\n",
      "Request Success\n",
      "80\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "'NoneType' object has no attribute 'text'\n",
      "81\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "82\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "83\n",
      "Request Success\n",
      "84\n",
      "reached exception\n",
      "HTTPSConnectionPool(host='autogalerie-dresden.kiapartner.de', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(\"hostname 'autogalerie-dresden.kiapartner.de' doesn't match either of 'mk.kia-dws.de', 'www.mk.kia-dws.de'\")))\n",
      "85\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "Must provide a string with at least 3 characters.\n",
      "86\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "87\n",
      "reached exception\n",
      "HTTPConnectionPool(host='www.citroen-haendler.de', port=80): Max retries exceeded with url: /fiedler-dresden/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4017971e50>: Failed to establish a new connection: [Errno 110] Connection timed out'))\n",
      "88\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "89\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "90\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "91\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "92\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "93\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "Must provide a string with at least 3 characters.\n",
      "94\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "95\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "96\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected en\n",
      "created Text Blob\n",
      "reached exception\n",
      "Translation API returned the input string unchanged.\n",
      "97\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "98\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "Must provide a string with at least 3 characters.\n",
      "99\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected fr\n",
      "created Text Blob\n",
      "file Written\n",
      "100\n",
      "reached exception\n",
      "('Connection aborted.', OSError(0, 'Error'))\n",
      "101\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "102\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "'NoneType' object has no attribute 'text'\n",
      "103\n",
      "reached exception\n",
      "HTTPConnectionPool(host='automobile-ebflorenz.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4013035ca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "104\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "105\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "106\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "Must provide a string with at least 3 characters.\n",
      "107\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected da\n",
      "created Text Blob\n",
      "file Written\n",
      "108\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "Must provide a string with at least 3 characters.\n",
      "109\n",
      "reached exception\n",
      "HTTPSConnectionPool(host='www.dresdner-reifen-zentrale.de', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1108)')))\n",
      "110\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "111\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "'NoneType' object has no attribute 'text'\n",
      "112\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "113\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "114\n",
      "reached exception\n",
      "Invalid URL 'www.reifen-ruehle.de': No schema supplied. Perhaps you meant http://www.reifen-ruehle.de?\n",
      "115\n",
      "reached exception\n",
      "HTTPConnectionPool(host='www.autohaus.ford.de', port=80): Max retries exceeded with url: /sachsengarage2/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f401393e520>: Failed to establish a new connection: [Errno 110] Connection timed out'))\n",
      "116\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "Must provide a string with at least 3 characters.\n",
      "117\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "'NoneType' object has no attribute 'text'\n",
      "118\n",
      "reached exception\n",
      "HTTPConnectionPool(host='www.autohaus-pattusch.dresden.vw-partner.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f40146700d0>: Failed to establish a new connection: [Errno 110] Connection timed out'))\n",
      "119\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "120\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "121\n",
      "reached exception\n",
      "('Connection aborted.', OSError(0, 'Error'))\n",
      "122\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "123\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "'NoneType' object has no attribute 'text'\n",
      "124\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "125\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "126\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "127\n",
      "Request Success\n",
      "128\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected en\n",
      "created Text Blob\n",
      "reached exception\n",
      "Translation API returned the input string unchanged.\n",
      "129\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected en\n",
      "created Text Blob\n",
      "reached exception\n",
      "Translation API returned the input string unchanged.\n",
      "130\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "'NoneType' object has no attribute 'text'\n",
      "131\n",
      "reached exception\n",
      "HTTPConnectionPool(host='www.gloeckner.chrysler.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4013d633a0>: Failed to establish a new connection: [Errno 113] No route to host'))\n",
      "132\n",
      "reached exception\n",
      "HTTPConnectionPool(host='www.dresden-sued.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4013d5c340>: Failed to establish a new connection: [Errno -2] Name or service not known'))\n",
      "133\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "134\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "Must provide a string with at least 3 characters.\n",
      "135\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected en\n",
      "created Text Blob\n",
      "reached exception\n",
      "Translation API returned the input string unchanged.\n",
      "136\n",
      "Request Success\n",
      "137\n",
      "reached exception\n",
      "Invalid URL 'www.kfz-brill.de': No schema supplied. Perhaps you meant http://www.kfz-brill.de?\n",
      "138\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "139\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected en\n",
      "created Text Blob\n",
      "reached exception\n",
      "Translation API returned the input string unchanged.\n",
      "140\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "141\n",
      "reached exception\n",
      "HTTPSConnectionPool(host='www.kfz-aufbereitung-dresden.de', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')))\n",
      "142\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "143\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "144\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "'NoneType' object has no attribute 'text'\n",
      "145\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "'NoneType' object has no attribute 'text'\n",
      "146\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "'NoneType' object has no attribute 'text'\n",
      "147\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "148\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "'NoneType' object has no attribute 'text'\n",
      "149\n",
      "reached exception\n",
      "Invalid URL 'www.carstyling.de': No schema supplied. Perhaps you meant http://www.carstyling.de?\n",
      "150\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected en\n",
      "created Text Blob\n",
      "reached exception\n",
      "Translation API returned the input string unchanged.\n",
      "151\n",
      "reached exception\n",
      "HTTPSConnectionPool(host='www.dresdner-reifen-zentrale.de', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1108)')))\n",
      "152\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "'NoneType' object has no attribute 'text'\n",
      "153\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "154\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "155\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "156\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "157\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "158\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "159\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "160\n",
      "reached exception\n",
      "HTTPConnectionPool(host='www.peugeothaendler.de', port=80): Max retries exceeded with url: /site/redirect.php?standortnr=486601/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4014117910>: Failed to establish a new connection: [Errno 110] Connection timed out'))\n",
      "161\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "162\n",
      "Request Success\n",
      "163\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "reached exception\n",
      "HTTP Error 403: Forbidden\n",
      "164\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "165\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "166\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "167\n",
      "reached exception\n",
      "HTTPSConnectionPool(host='braune.kiapartner.de', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(\"hostname 'braune.kiapartner.de' doesn't match either of 'mk.kia-dws.de', 'www.mk.kia-dws.de'\")))\n",
      "168\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "'NoneType' object has no attribute 'text'\n",
      "169\n",
      "Request Success\n",
      "170\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "Must provide a string with at least 3 characters.\n",
      "171\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "'NoneType' object has no attribute 'text'\n",
      "172\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "173\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected en\n",
      "created Text Blob\n",
      "reached exception\n",
      "Translation API returned the input string unchanged.\n",
      "174\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "175\n",
      "Request Success\n",
      "176\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "177\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "reached exception\n",
      "'NoneType' object has no attribute 'text'\n",
      "178\n",
      "Request Success\n",
      "179\n",
      "Request Success\n",
      "180\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "181\n",
      "Request Success\n",
      "182\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "183\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n",
      "184\n",
      "Request Success\n",
      "gathered Soup\n",
      "found deText\n",
      "Language Detected de\n",
      "created Text Blob\n",
      "file Written\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "{'http://www.opelhaendler.de/autohaus-dresden_dresden/': AttributeError(\"'NoneType' object has no attribute 'text'\"),\n",
       " 'http://www.hanisch.hyundai.de/': AttributeError(\"'NoneType' object has no attribute 'text'\"),\n",
       " 'http://www.dresdner-reifen-zentrale.de/': requests.exceptions.SSLError(urllib3.exceptions.MaxRetryError(\"HTTPSConnectionPool(host='www.dresdner-reifen-zentrale.de', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1108)')))\")),\n",
       " 'http://www.euromaster.de/': textblob.exceptions.NotTranslated('Translation API returned the input string unchanged.'),\n",
       " 'http://www.lack-werk.de/': requests.exceptions.ConnectionError(urllib3.exceptions.ProtocolError('Connection aborted.',\n",
       "                                                                      http.client.RemoteDisconnected('Remote end closed connection without response'))),\n",
       " 'http://partner.volkswagen.de/vwcms/partner_de/virtualmaster/de705990.metanav.html/': 404,\n",
       " 'http://www.weyand-werkstatt.de/': textblob.exceptions.TranslatorError('Must provide a string with at least 3 characters.'),\n",
       " 'http://handel.suzuki.de/tross/': textblob.exceptions.TranslatorError('Must provide a string with at least 3 characters.'),\n",
       " 'http://www.renault.de/handler/anders/': 404,\n",
       " 'http://www.autoklimazentrum.de/': AttributeError(\"'NoneType' object has no attribute 'text'\"),\n",
       " 'http://www.karosserie-zdzieblik-dresden.de': requests.exceptions.ConnectionError(urllib3.exceptions.MaxRetryError(\"HTTPConnectionPool(host='www.karosserie-zdzieblik-dresden.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f40134a1d00>: Failed to establish a new connection: [Errno -2] Name or service not known'))\")),\n",
       " 'http://www.auto-winter.de/': textblob.exceptions.TranslatorError('Must provide a string with at least 3 characters.'),\n",
       " 'http://www.elbkontor.seat.de/': textblob.exceptions.TranslatorError('Must provide a string with at least 3 characters.'),\n",
       " 'http://www.exklusive-kollektion.de/': AttributeError(\"'NoneType' object has no attribute 'text'\"),\n",
       " 'http://www.dresden-reifen.de/': textblob.exceptions.TranslatorError('Must provide a string with at least 3 characters.'),\n",
       " 'http://www.kfz-meisterbetrieb-janopitz.de/': AttributeError(\"'NoneType' object has no attribute 'text'\"),\n",
       " 'http://www.kfz-fluegel.de/': textblob.exceptions.NotTranslated('Translation API returned the input string unchanged.'),\n",
       " 'http://www.drecatec.de/': AttributeError(\"'NoneType' object has no attribute 'text'\"),\n",
       " 'http://www.partner.volvocars.de/sachsengarage/dresdner-heide/': requests.exceptions.ConnectionError(urllib3.exceptions.MaxRetryError(\"HTTPConnectionPool(host='www.partner.volvocars.de', port=80): Max retries exceeded with url: /sachsengarage/dresdner-heide/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4012e00940>: Failed to establish a new connection: [Errno 111] Connection refused'))\")),\n",
       " 'http://www.schiemann.hyundai.de/': requests.exceptions.ConnectionError(urllib3.exceptions.MaxRetryError(\"HTTPConnectionPool(host='www.schiemann.hyundai.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4012e091f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\")),\n",
       " 'http://www.autoservice-weixdorf.de/': textblob.exceptions.TranslatorError('Must provide a string with at least 3 characters.'),\n",
       " 'http://www.menzel.go1a.de/': textblob.exceptions.NotTranslated('Translation API returned the input string unchanged.'),\n",
       " 'http://www.gloeckner.chrysler.de/': requests.exceptions.ConnectionError(urllib3.exceptions.MaxRetryError(\"HTTPConnectionPool(host='www.gloeckner.chrysler.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4013d633a0>: Failed to establish a new connection: [Errno 113] No route to host'))\")),\n",
       " 'http://www.autohaus-hoernigundjaeger.de/': AttributeError(\"'NoneType' object has no attribute 'text'\"),\n",
       " 'http://www.opelhaendler.de/autohaus-peschel_dresden/': AttributeError(\"'NoneType' object has no attribute 'text'\"),\n",
       " 'http://www.autoservice-hartmann.de/': AttributeError(\"'NoneType' object has no attribute 'text'\"),\n",
       " 'http://www.wm.de/de/werkstattkonzepte/transporterprofi/werkstatt-suche.html/': 404,\n",
       " 'http://www.reifendoering.de/': AttributeError(\"'NoneType' object has no attribute 'text'\"),\n",
       " 'http://www.kromer-dresden.de/': 403,\n",
       " 'http://www.autodaum.go1a.de/': textblob.exceptions.NotTranslated('Translation API returned the input string unchanged.'),\n",
       " 'http://www.audi.de/partner/autohaus-holm-wirthgen/': textblob.exceptions.TranslatorError('Must provide a string with at least 3 characters.'),\n",
       " 'http://www.autoklinik-dresden.de': textblob.exceptions.TranslatorError('Must provide a string with at least 3 characters.'),\n",
       " 'http://www.ams-hannss.de/': requests.exceptions.ConnectionError(urllib3.exceptions.MaxRetryError(\"HTTPConnectionPool(host='www.ams-hannss.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f40144d6340>: Failed to establish a new connection: [Errno -2] Name or service not known'))\")),\n",
       " 'http://www.autoleuner.go1a.de/': textblob.exceptions.NotTranslated('Translation API returned the input string unchanged.'),\n",
       " 'http://www.renault.de/handler/ah_trobisch/': 404,\n",
       " 'http://www.lexusforum-dresden.de/': 403,\n",
       " 'http://www.toyota-partner.de/ais-radebeul/': textblob.exceptions.NotTranslated('Translation API returned the input string unchanged.'),\n",
       " 'http://strehle.kiapartner.de/': requests.exceptions.SSLError(urllib3.exceptions.MaxRetryError('HTTPSConnectionPool(host=\\'strehle.kiapartner.de\\', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(\"hostname \\'strehle.kiapartner.de\\' doesn\\'t match either of \\'mk.kia-dws.de\\', \\'www.mk.kia-dws.de\\'\")))')),\n",
       " 'http://www.citroen-haendler.de/heider-dresden/': requests.exceptions.ConnectionError(urllib3.exceptions.MaxRetryError(\"HTTPConnectionPool(host='www.citroen-haendler.de', port=80): Max retries exceeded with url: /heider-dresden/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4012f8d0a0>: Failed to establish a new connection: [Errno 110] Connection timed out'))\")),\n",
       " 'http://www.opelhaendler.de/autohaus-peschel2_dresden/': AttributeError(\"'NoneType' object has no attribute 'text'\"),\n",
       " 'https://www.kfz-service-bretschneider.de': requests.exceptions.ConnectionError(urllib3.exceptions.ProtocolError('Connection aborted.',\n",
       "                                                                      OSError(0,\n",
       "                                                                              'Error'))),\n",
       " 'http://www.saab-erleben.de/': requests.exceptions.ConnectionError(urllib3.exceptions.MaxRetryError(\"HTTPConnectionPool(host='www.saab-erleben.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4013fab1f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\")),\n",
       " 'http://www.sb-autowaesche-dresden.de/': AttributeError(\"'NoneType' object has no attribute 'text'\"),\n",
       " 'http://www.citroen-haendler.de/bernhardt-dresden/': requests.exceptions.ConnectionError(urllib3.exceptions.MaxRetryError(\"HTTPConnectionPool(host='www.citroen-haendler.de', port=80): Max retries exceeded with url: /bernhardt-dresden/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4013ef63a0>: Failed to establish a new connection: [Errno 110] Connection timed out'))\")),\n",
       " 'http://www.renault.de/handler/ah_gretschel/': 404,\n",
       " 'http://www.mazda-autohaus-rausch.de/': AttributeError(\"'NoneType' object has no attribute 'text'\"),\n",
       " 'http://auto-bruhns.seat.de/': 500,\n",
       " 'http://autogalerie-dresden.kiapartner.de/': requests.exceptions.SSLError(urllib3.exceptions.MaxRetryError('HTTPSConnectionPool(host=\\'autogalerie-dresden.kiapartner.de\\', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(\"hostname \\'autogalerie-dresden.kiapartner.de\\' doesn\\'t match either of \\'mk.kia-dws.de\\', \\'www.mk.kia-dws.de\\'\")))')),\n",
       " 'http://www.honda-fugel.de/': textblob.exceptions.TranslatorError('Must provide a string with at least 3 characters.'),\n",
       " 'http://www.citroen-haendler.de/fiedler-dresden/': requests.exceptions.ConnectionError(urllib3.exceptions.MaxRetryError(\"HTTPConnectionPool(host='www.citroen-haendler.de', port=80): Max retries exceeded with url: /fiedler-dresden/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4017971e50>: Failed to establish a new connection: [Errno 110] Connection timed out'))\")),\n",
       " 'http://www.motor-visionen.de': textblob.exceptions.TranslatorError('Must provide a string with at least 3 characters.'),\n",
       " 'http://www.oehlschlaeger.go1a.de/': textblob.exceptions.NotTranslated('Translation API returned the input string unchanged.'),\n",
       " 'http://www.atp-dresden.de/': textblob.exceptions.TranslatorError('Must provide a string with at least 3 characters.'),\n",
       " 'https://www.autoklug.de/': requests.exceptions.ConnectionError(urllib3.exceptions.ProtocolError('Connection aborted.',\n",
       "                                                                      OSError(0,\n",
       "                                                                              'Error'))),\n",
       " 'http://www.opelhaendler.de/autohaus-maetschke_dresden/': AttributeError(\"'NoneType' object has no attribute 'text'\"),\n",
       " 'http://automobile-ebflorenz.de/': requests.exceptions.ConnectionError(urllib3.exceptions.MaxRetryError(\"HTTPConnectionPool(host='automobile-ebflorenz.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4013035ca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))\")),\n",
       " 'http://www.automasseur.de': textblob.exceptions.TranslatorError('Must provide a string with at least 3 characters.'),\n",
       " 'http://www.ergotherapie-et.de/': AttributeError(\"'NoneType' object has no attribute 'text'\"),\n",
       " 'www.reifen-ruehle.de': requests.exceptions.MissingSchema(\"Invalid URL 'www.reifen-ruehle.de': No schema supplied. Perhaps you meant http://www.reifen-ruehle.de?\"),\n",
       " 'http://www.autohaus.ford.de/sachsengarage2/': requests.exceptions.ConnectionError(urllib3.exceptions.MaxRetryError(\"HTTPConnectionPool(host='www.autohaus.ford.de', port=80): Max retries exceeded with url: /sachsengarage2/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f401393e520>: Failed to establish a new connection: [Errno 110] Connection timed out'))\")),\n",
       " 'http://www.tom-automobile.de/': textblob.exceptions.TranslatorError('Must provide a string with at least 3 characters.'),\n",
       " 'http://www.opelhaendler.de/autohaus-behnisch_dresden/': AttributeError(\"'NoneType' object has no attribute 'text'\"),\n",
       " 'http://www.autohaus-pattusch.dresden.vw-partner.de/': requests.exceptions.ConnectionError(urllib3.exceptions.MaxRetryError(\"HTTPConnectionPool(host='www.autohaus-pattusch.dresden.vw-partner.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f40146700d0>: Failed to establish a new connection: [Errno 110] Connection timed out'))\")),\n",
       " 'https://www.autoglas-eichler.de/': requests.exceptions.ConnectionError(urllib3.exceptions.ProtocolError('Connection aborted.',\n",
       "                                                                      OSError(0,\n",
       "                                                                              'Error'))),\n",
       " 'http://www.auto-lust.de/': AttributeError(\"'NoneType' object has no attribute 'text'\"),\n",
       " 'http://www.renault.de/handler/friedewald/': 404,\n",
       " 'http://www.ais-toyota.de/': textblob.exceptions.NotTranslated('Translation API returned the input string unchanged.'),\n",
       " 'http://www.avag.eu/standorte/standortkarte.html/': textblob.exceptions.NotTranslated('Translation API returned the input string unchanged.'),\n",
       " 'http://www.opelhaendler.de/autohaus-dresden_dresden3/': AttributeError(\"'NoneType' object has no attribute 'text'\"),\n",
       " 'http://www.dresden-sued.de/': requests.exceptions.ConnectionError(urllib3.exceptions.MaxRetryError(\"HTTPConnectionPool(host='www.dresden-sued.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4013d5c340>: Failed to establish a new connection: [Errno -2] Name or service not known'))\")),\n",
       " 'http://autohaus-leubnitz.seat.de/': textblob.exceptions.TranslatorError('Must provide a string with at least 3 characters.'),\n",
       " 'http://www.lack-fischer.de/': textblob.exceptions.NotTranslated('Translation API returned the input string unchanged.'),\n",
       " 'http://www.bmw.de/nl_dresden/': 404,\n",
       " 'www.kfz-brill.de': requests.exceptions.MissingSchema(\"Invalid URL 'www.kfz-brill.de': No schema supplied. Perhaps you meant http://www.kfz-brill.de?\"),\n",
       " 'http://dkt.skoda-auto.de/': textblob.exceptions.NotTranslated('Translation API returned the input string unchanged.'),\n",
       " 'http://www.kfz-aufbereitung-dresden.de/': requests.exceptions.SSLError(urllib3.exceptions.MaxRetryError(\"HTTPSConnectionPool(host='www.kfz-aufbereitung-dresden.de', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')))\")),\n",
       " 'http://www.tg-automobile.hyundai.de/': AttributeError(\"'NoneType' object has no attribute 'text'\"),\n",
       " 'http://www.auto23.de/': AttributeError(\"'NoneType' object has no attribute 'text'\"),\n",
       " 'http://www.auto-zilt.de/': AttributeError(\"'NoneType' object has no attribute 'text'\"),\n",
       " 'www.carstyling.de': requests.exceptions.MissingSchema(\"Invalid URL 'www.carstyling.de': No schema supplied. Perhaps you meant http://www.carstyling.de?\"),\n",
       " 'http://www.identica-bertholdt.de/': textblob.exceptions.NotTranslated('Translation API returned the input string unchanged.'),\n",
       " 'http://www.fskdd.de/': AttributeError(\"'NoneType' object has no attribute 'text'\"),\n",
       " 'http://www.peugeothaendler.de/site/redirect.php?standortnr=486601/': requests.exceptions.ConnectionError(urllib3.exceptions.MaxRetryError(\"HTTPConnectionPool(host='www.peugeothaendler.de', port=80): Max retries exceeded with url: /site/redirect.php?standortnr=486601/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4014117910>: Failed to establish a new connection: [Errno 110] Connection timed out'))\")),\n",
       " 'http://www.vergoelst.de/haendlersuche/': 404,\n",
       " 'http://www.smart-sternauto-dresden.de/': <HTTPError 403: 'Forbidden'>,\n",
       " 'http://braune.kiapartner.de/': requests.exceptions.SSLError(urllib3.exceptions.MaxRetryError('HTTPSConnectionPool(host=\\'braune.kiapartner.de\\', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(\"hostname \\'braune.kiapartner.de\\' doesn\\'t match either of \\'mk.kia-dws.de\\', \\'www.mk.kia-dws.de\\'\")))')),\n",
       " 'http://www.opelhaendler.de/autohaus-israel_dresden/': AttributeError(\"'NoneType' object has no attribute 'text'\"),\n",
       " 'http://www.autohof-dresden.de/': 403,\n",
       " 'http://www.automeisterei.de/': textblob.exceptions.TranslatorError('Must provide a string with at least 3 characters.'),\n",
       " 'http://www.autoservice-barth-dresden.de/': AttributeError(\"'NoneType' object has no attribute 'text'\"),\n",
       " 'http://www.blumentritt-petersen.go1a.de/': textblob.exceptions.NotTranslated('Translation API returned the input string unchanged.'),\n",
       " 'http://www.renault.de/handler/dresdener_auto_ag/': 404,\n",
       " 'http://www.fahrzeugausbau-fischer.de/': AttributeError(\"'NoneType' object has no attribute 'text'\"),\n",
       " 'http://www.werkstatttube.de/werkstatt/pahner-jan.html/': 404,\n",
       " 'http://www.lockwitz-intern.de/kfz-klinnert.html': 404,\n",
       " 'http://www.wm.de/de/unternehmen/standorte/details/dresden.html/': 404}"
      ]
     },
     "execution_count": 99,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "startScraping(dataset['homepage'],4)\n",
    "notScraped\n",
    "# !jupyter nb"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 97,
   "metadata": {},
   "outputs": [
    {
     "ename": "SSLError",
     "evalue": "HTTPSConnectionPool(host='www.dresdner-reifen-zentrale.de', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1108)')))",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mSSLCertVerificationError\u001b[0m                  Traceback (most recent call last)",
      "\u001b[0;32m~/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py\u001b[0m in \u001b[0;36murlopen\u001b[0;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)\u001b[0m\n\u001b[1;32m    669\u001b[0m             \u001b[0;31m# Make the request on the httplib connection object.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 670\u001b[0;31m             httplib_response = self._make_request(\n\u001b[0m\u001b[1;32m    671\u001b[0m                 \u001b[0mconn\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py\u001b[0m in \u001b[0;36m_make_request\u001b[0;34m(self, conn, method, url, timeout, chunked, **httplib_request_kw)\u001b[0m\n\u001b[1;32m    380\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 381\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_validate_conn\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mconn\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    382\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0mSocketTimeout\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mBaseSSLError\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py\u001b[0m in \u001b[0;36m_validate_conn\u001b[0;34m(self, conn)\u001b[0m\n\u001b[1;32m    975\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mgetattr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mconn\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"sock\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m  \u001b[0;31m# AppEngine might not have  `.sock`\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 976\u001b[0;31m             \u001b[0mconn\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mconnect\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    977\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.8/site-packages/urllib3/connection.py\u001b[0m in \u001b[0;36mconnect\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    360\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 361\u001b[0;31m         self.sock = ssl_wrap_socket(\n\u001b[0m\u001b[1;32m    362\u001b[0m             \u001b[0msock\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mconn\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.8/site-packages/urllib3/util/ssl_.py\u001b[0m in \u001b[0;36mssl_wrap_socket\u001b[0;34m(sock, keyfile, certfile, cert_reqs, ca_certs, server_hostname, ssl_version, ciphers, ssl_context, ca_cert_dir, key_password, ca_cert_data)\u001b[0m\n\u001b[1;32m    376\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mHAS_SNI\u001b[0m \u001b[0;32mand\u001b[0m \u001b[0mserver_hostname\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 377\u001b[0;31m             \u001b[0;32mreturn\u001b[0m \u001b[0mcontext\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwrap_socket\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msock\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mserver_hostname\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mserver_hostname\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    378\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.8/ssl.py\u001b[0m in \u001b[0;36mwrap_socket\u001b[0;34m(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, session)\u001b[0m\n\u001b[1;32m    499\u001b[0m         \u001b[0;31m# ctx._wrap_socket()\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 500\u001b[0;31m         return self.sslsocket_class._create(\n\u001b[0m\u001b[1;32m    501\u001b[0m             \u001b[0msock\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0msock\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.8/ssl.py\u001b[0m in \u001b[0;36m_create\u001b[0;34m(cls, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, context, session)\u001b[0m\n\u001b[1;32m   1039\u001b[0m                         \u001b[0;32mraise\u001b[0m \u001b[0mValueError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"do_handshake_on_connect should not be specified for non-blocking sockets\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1040\u001b[0;31m                     \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdo_handshake\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1041\u001b[0m             \u001b[0;32mexcept\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0mOSError\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mValueError\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.8/ssl.py\u001b[0m in \u001b[0;36mdo_handshake\u001b[0;34m(self, block)\u001b[0m\n\u001b[1;32m   1308\u001b[0m                 \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msettimeout\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;32mNone\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1309\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_sslobj\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdo_handshake\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1310\u001b[0m         \u001b[0;32mfinally\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mSSLCertVerificationError\u001b[0m: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1108)",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mMaxRetryError\u001b[0m                             Traceback (most recent call last)",
      "\u001b[0;32m~/anaconda3/lib/python3.8/site-packages/requests/adapters.py\u001b[0m in \u001b[0;36msend\u001b[0;34m(self, request, stream, timeout, verify, cert, proxies)\u001b[0m\n\u001b[1;32m    438\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mchunked\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 439\u001b[0;31m                 resp = conn.urlopen(\n\u001b[0m\u001b[1;32m    440\u001b[0m                     \u001b[0mmethod\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mrequest\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmethod\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py\u001b[0m in \u001b[0;36murlopen\u001b[0;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)\u001b[0m\n\u001b[1;32m    723\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 724\u001b[0;31m             retries = retries.increment(\n\u001b[0m\u001b[1;32m    725\u001b[0m                 \u001b[0mmethod\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0murl\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0merror\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0me\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0m_pool\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0m_stacktrace\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0msys\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mexc_info\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m2\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.8/site-packages/urllib3/util/retry.py\u001b[0m in \u001b[0;36mincrement\u001b[0;34m(self, method, url, response, error, _pool, _stacktrace)\u001b[0m\n\u001b[1;32m    438\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mnew_retry\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mis_exhausted\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 439\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0mMaxRetryError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0m_pool\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0murl\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0merror\u001b[0m \u001b[0;32mor\u001b[0m \u001b[0mResponseError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcause\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    440\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mMaxRetryError\u001b[0m: HTTPSConnectionPool(host='www.dresdner-reifen-zentrale.de', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1108)')))",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mSSLError\u001b[0m                                  Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-97-65bae7ea288c>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mresponse\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mrequests\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdataset\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mhomepage\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m10\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mverify\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mcertifi\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwhere\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/anaconda3/lib/python3.8/site-packages/requests/api.py\u001b[0m in \u001b[0;36mget\u001b[0;34m(url, params, **kwargs)\u001b[0m\n\u001b[1;32m     74\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     75\u001b[0m     \u001b[0mkwargs\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msetdefault\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'allow_redirects'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;32mTrue\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 76\u001b[0;31m     \u001b[0;32mreturn\u001b[0m \u001b[0mrequest\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'get'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0murl\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mparams\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mparams\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     77\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     78\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.8/site-packages/requests/api.py\u001b[0m in \u001b[0;36mrequest\u001b[0;34m(method, url, **kwargs)\u001b[0m\n\u001b[1;32m     59\u001b[0m     \u001b[0;31m# cases, and look like a memory leak in others.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     60\u001b[0m     \u001b[0;32mwith\u001b[0m \u001b[0msessions\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mSession\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0msession\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 61\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0msession\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrequest\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmethod\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mmethod\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0murl\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0murl\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     62\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     63\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.8/site-packages/requests/sessions.py\u001b[0m in \u001b[0;36mrequest\u001b[0;34m(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)\u001b[0m\n\u001b[1;32m    528\u001b[0m         }\n\u001b[1;32m    529\u001b[0m         \u001b[0msend_kwargs\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mupdate\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msettings\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 530\u001b[0;31m         \u001b[0mresp\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msend\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mprep\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0msend_kwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    531\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    532\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mresp\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.8/site-packages/requests/sessions.py\u001b[0m in \u001b[0;36msend\u001b[0;34m(self, request, **kwargs)\u001b[0m\n\u001b[1;32m    663\u001b[0m             \u001b[0;31m# Redirect resolving generator.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    664\u001b[0m             \u001b[0mgen\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mresolve_redirects\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mr\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrequest\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 665\u001b[0;31m             \u001b[0mhistory\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0mresp\u001b[0m \u001b[0;32mfor\u001b[0m \u001b[0mresp\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mgen\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    666\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    667\u001b[0m             \u001b[0mhistory\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.8/site-packages/requests/sessions.py\u001b[0m in \u001b[0;36m<listcomp>\u001b[0;34m(.0)\u001b[0m\n\u001b[1;32m    663\u001b[0m             \u001b[0;31m# Redirect resolving generator.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    664\u001b[0m             \u001b[0mgen\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mresolve_redirects\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mr\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrequest\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 665\u001b[0;31m             \u001b[0mhistory\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0mresp\u001b[0m \u001b[0;32mfor\u001b[0m \u001b[0mresp\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mgen\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    666\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    667\u001b[0m             \u001b[0mhistory\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.8/site-packages/requests/sessions.py\u001b[0m in \u001b[0;36mresolve_redirects\u001b[0;34m(self, resp, req, stream, timeout, verify, cert, proxies, yield_requests, **adapter_kwargs)\u001b[0m\n\u001b[1;32m    235\u001b[0m             \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    236\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 237\u001b[0;31m                 resp = self.send(\n\u001b[0m\u001b[1;32m    238\u001b[0m                     \u001b[0mreq\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    239\u001b[0m                     \u001b[0mstream\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mstream\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.8/site-packages/requests/sessions.py\u001b[0m in \u001b[0;36msend\u001b[0;34m(self, request, **kwargs)\u001b[0m\n\u001b[1;32m    641\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    642\u001b[0m         \u001b[0;31m# Send the request\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 643\u001b[0;31m         \u001b[0mr\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0madapter\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msend\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mrequest\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    644\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    645\u001b[0m         \u001b[0;31m# Total elapsed time of the request (approximately)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.8/site-packages/requests/adapters.py\u001b[0m in \u001b[0;36msend\u001b[0;34m(self, request, stream, timeout, verify, cert, proxies)\u001b[0m\n\u001b[1;32m    512\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0misinstance\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0me\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mreason\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0m_SSLError\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    513\u001b[0m                 \u001b[0;31m# This branch is for urllib3 v1.22 and later.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 514\u001b[0;31m                 \u001b[0;32mraise\u001b[0m \u001b[0mSSLError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0me\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrequest\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mrequest\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    515\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    516\u001b[0m             \u001b[0;32mraise\u001b[0m \u001b[0mConnectionError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0me\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrequest\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mrequest\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mSSLError\u001b[0m: HTTPSConnectionPool(host='www.dresdner-reifen-zentrale.de', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1108)')))"
     ]
    }
   ],
   "source": [
    "response = requests.get(dataset.homepage[10], verify = certifi.where())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
